# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow.setMaximumSize(QtCore.QSize(500, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 700))
        self.centralwidget.setMaximumSize(QtCore.QSize(500, 700))
        self.centralwidget.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_1.setStyleSheet("border:0")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.Error = QtWidgets.QLabel(self.frame_1)
        self.Error.setGeometry(QtCore.QRect(150, 10, 191, 19))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Error.setFont(font)
        self.Error.setStyleSheet("color: rgb(239, 41, 41);")
        self.Error.setObjectName("Error")
        self.verticalLayout.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("border:0")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(100, 380, 92, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox::indicator{\n"
"border: 2px solid rgb(136, 138, 133);\n"
"border-radius: 7px;\n"
"width: 15px;\n"
"heigth: 15px;\n"
"background-color: rgb(186, 189, 182);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"border: 2px solid rgb(204, 0, 0);\n"
"background-color: rgbrgb(239, 41, 41);\n"
"}\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.Password = QtWidgets.QLineEdit(self.frame_2)
        self.Password.setEnabled(True)
        self.Password.setGeometry(QtCore.QRect(100, 320, 280, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Password.setFont(font)
        self.Password.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(186, 189, 182);\n"
"border-radius: 5px;\n"
"padding: 15px;\n"
"    background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(122, 6, 6);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(239, 41, 41);\n"
"color: rgb(200, 200, 200);\n"
"}\n"
"")
        self.Password.setText("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.Avatar = QtWidgets.QFrame(self.frame_2)
        self.Avatar.setGeometry(QtCore.QRect(180, 90, 121, 121))
        self.Avatar.setStyleSheet("background-image: url(:/Avatar/Design/icones/avatar.png);\n"
"border: 2px  solid rgb(239, 41, 41);\n"
"border-radius: 60px;\n"
"")
        self.Avatar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Avatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Avatar.setObjectName("Avatar")
        self.LOGINButton = QtWidgets.QPushButton(self.frame_2)
        self.LOGINButton.setEnabled(True)
        self.LOGINButton.setGeometry(QtCore.QRect(140, 420, 200, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.LOGINButton.setFont(font)
        self.LOGINButton.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(136, 138, 133);\n"
"    border: 2px solid rgb(239, 41, 41);\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(239, 41, 41);\n"
"    border: 2px solid rgb(239, 41, 41);\n"
"}")
        self.LOGINButton.setObjectName("LOGINButton")
        self.User = QtWidgets.QLineEdit(self.frame_2)
        self.User.setEnabled(True)
        self.User.setGeometry(QtCore.QRect(100, 260, 280, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.User.setFont(font)
        self.User.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(186, 189, 182);\n"
"border-radius: 5px;\n"
"padding: 15px;\n"
"background-color: rgb(136, 138, 133);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(122, 6, 6);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(239, 41, 41);\n"
"color: rgb(200, 200, 200);\n"
"}\n"
"")
        self.User.setText("")
        self.User.setObjectName("User")
        self.SignUpButton = QtWidgets.QPushButton(self.frame_2)
        self.SignUpButton.setGeometry(QtCore.QRect(280, 540, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SignUpButton.setFont(font)
        self.SignUpButton.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:rgb(239, 41, 41);\n"
"    \n"
"}")
        self.SignUpButton.setObjectName("SignUpButton")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(100, 540, 161, 20))
        self.label.setObjectName("label")
        self.SignIn = QtWidgets.QLabel(self.frame_2)
        self.SignIn.setGeometry(QtCore.QRect(190, 20, 127, 34))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.SignIn.setFont(font)
        self.SignIn.setStyleSheet("color: rgb(255, 255, 255);")
        self.SignIn.setObjectName("SignIn")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(35, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setStyleSheet("border:0")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Logo = QtWidgets.QFrame(self.frame_3)
        self.Logo.setGeometry(QtCore.QRect(40, 0, 150, 40))
        self.Logo.setMaximumSize(QtCore.QSize(150, 40))
        self.Logo.setStyleSheet("background-image: url(:/Bosh/Design/icones/bosch-logo_2_150x40.png);\n"
"\n"
"border-radius: 5px")
        self.Logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Logo.setObjectName("Logo")
        self.Ua = QtWidgets.QFrame(self.frame_3)
        self.Ua.setGeometry(QtCore.QRect(300, 0, 161, 80))
        self.Ua.setStyleSheet("background-repeat:none;\n"
"border-radius: 5px;\n"
"background-image: url(:/Bosh/Design/icones/UA1_150x40.png);")
        self.Ua.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Ua.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Ua.setObjectName("Ua")
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Error.setText(_translate("MainWindow", "Error - USER NOT FOUND"))
        self.checkBox.setText(_translate("MainWindow", "Save User"))
        self.Password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.LOGINButton.setText(_translate("MainWindow", "LOGIN"))
        self.User.setPlaceholderText(_translate("MainWindow", "User"))
        self.SignUpButton.setText(_translate("MainWindow", "Sign Up"))
        self.label.setText(_translate("MainWindow", "Don\'t have an Account ?"))
        self.SignIn.setText(_translate("MainWindow", "Sign In"))
import file_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())