# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_vf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_1.setStyleSheet("border:0")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Menu = QtWidgets.QFrame(self.frame_1)
        self.Menu.setMaximumSize(QtCore.QSize(55, 16777215))
        self.Menu.setStyleSheet("border:o;\n"
"background-color: rgb(211, 215, 207);")
        self.Menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu.setObjectName("Menu")
        self.MenuButton = QtWidgets.QPushButton(self.Menu)
        self.MenuButton.setGeometry(QtCore.QRect(10, 10, 40, 30))
        self.MenuButton.setMinimumSize(QtCore.QSize(1, 0))
        self.MenuButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/Menu/Design/icones/menu_40x30.png);\n"
"border-radius:2px;\n"
"}")
        self.MenuButton.setText("")
        self.MenuButton.setIconSize(QtCore.QSize(20, 20))
        self.MenuButton.setObjectName("MenuButton")
        self.horizontalLayout_2.addWidget(self.Menu)
        self.Title = QtWidgets.QFrame(self.frame_1)
        self.Title.setMinimumSize(QtCore.QSize(0, 50))
        self.Title.setStyleSheet("border:0;\n"
"background-color: rgb(211, 215, 207);")
        self.Title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title.setObjectName("Title")
        self.horizontalLayout_2.addWidget(self.Title)
        self.verticalLayout.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("border:0")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Left = QtWidgets.QFrame(self.frame_2)
        self.Left.setMinimumSize(QtCore.QSize(55, 0))
        self.Left.setMaximumSize(QtCore.QSize(55, 16777215))
        self.Left.setStyleSheet("border:0 ; \n"
"background-color: rgb(211, 215, 207);")
        self.Left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Left.setObjectName("Left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Left)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TOP_BUTTON = QtWidgets.QFrame(self.Left)
        self.TOP_BUTTON.setMaximumSize(QtCore.QSize(150, 16777215))
        self.TOP_BUTTON.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TOP_BUTTON.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TOP_BUTTON.setObjectName("TOP_BUTTON")
        self.Home = QtWidgets.QPushButton(self.TOP_BUTTON)
        self.Home.setGeometry(QtCore.QRect(0, 120, 130, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Home.setFont(font)
        self.Home.setStyleSheet("QPushButton{\n"
"     \n"
"    border-radius: 10px;\n"
"    background-repeat:none;\n"
"    background-image: url(:/Menu/Design/icones/home-icon-silhouette_1_50x50.png);\n"
"    padding-left: 50px; \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(136, 138, 133);\n"
"    \n"
"}")
        self.Home.setObjectName("Home")
        self.NewUnidade = QtWidgets.QPushButton(self.TOP_BUTTON)
        self.NewUnidade.setGeometry(QtCore.QRect(0, 270, 130, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.NewUnidade.setFont(font)
        self.NewUnidade.setStyleSheet("QPushButton{\n"
"    padding: 5px 7px; \n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(186, 189, 182);\n"
"    color: rgb(255, 255, 255);\n"
"    background-repeat:none;\n"
"    background-image: url(:/Menu/Design/icones/plus_50x50.png);\n"
"    background-position: center left;\n"
"    padding-left: 50px; \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: rgb(136, 138, 133);\n"
"}")
        self.NewUnidade.setFlat(False)
        self.NewUnidade.setObjectName("NewUnidade")
        self.verticalLayout_2.addWidget(self.TOP_BUTTON)
        self.Account = QtWidgets.QPushButton(self.Left)
        self.Account.setMinimumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Account.setFont(font)
        self.Account.setStyleSheet("QPushButton{\n"
"    padding: 5px 7px; \n"
"    border-radius: 10px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-repeat:none;\n"
"    \n"
"    background-image: url(:/Menu/Design/icones/pngfind.com-man-head-silhouette-png-6227673_50x50.png);\n"
"\n"
"    background-position: center left;\n"
"    padding-left: 54px; \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: rgb(136, 138, 133);\n"
"}")
        self.Account.setObjectName("Account")
        self.verticalLayout_2.addWidget(self.Account)
        self.Settings = QtWidgets.QPushButton(self.Left)
        self.Settings.setMinimumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Settings.setFont(font)
        self.Settings.setStyleSheet("QPushButton{\n"
"    padding: 5px 7px; \n"
"    border-radius: 10px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-repeat:none;\n"
"    \n"
"    background-image: url(:/Menu/Design/icones/settings_50x50.png);\n"
"    background-position: center left;\n"
"    padding-left: 55px; \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"        background-color: rgb(136, 138, 133);\n"
"}")
        self.Settings.setObjectName("Settings")
        self.verticalLayout_2.addWidget(self.Settings)
        self.horizontalLayout.addWidget(self.Left)
        self.Mid = QtWidgets.QFrame(self.frame_2)
        self.Mid.setStyleSheet("border:0")
        self.Mid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Mid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Mid.setObjectName("Mid")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Mid)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.Mid)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 894, 481))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.Sensor1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.Sensor1.setMinimumSize(QtCore.QSize(200, 200))
        self.Sensor1.setMaximumSize(QtCore.QSize(1000, 1000))
        self.Sensor1.setStyleSheet("")
        self.Sensor1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Sensor1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Sensor1.setObjectName("Sensor1")
        self.Sensor1Button = QtWidgets.QPushButton(self.Sensor1)
        self.Sensor1Button.setEnabled(True)
        self.Sensor1Button.setGeometry(QtCore.QRect(0, 150, 200, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Sensor1Button.setFont(font)
        self.Sensor1Button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(136, 138, 133);\n"
"    border: 2px  ;\n"
"    border-radius: 20px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(239, 41, 41);\n"
"    border: 2px solid rgb(239, 41, 41);\n"
"}")
        self.Sensor1Button.setObjectName("Sensor1Button")
        self.Sensor1Label = QtWidgets.QLabel(self.Sensor1)
        self.Sensor1Label.setGeometry(QtCore.QRect(20, 30, 151, 111))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(42)
        font.setBold(False)
        font.setWeight(50)
        self.Sensor1Label.setFont(font)
        self.Sensor1Label.setStyleSheet("border: 2px solid rgb(239, 41, 41);\n"
"    border-radius: 20px;\n"
"")
        self.Sensor1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Sensor1Label.setObjectName("Sensor1Label")
        self.gridLayout.addWidget(self.Sensor1, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.Mid)
        self.Right = QtWidgets.QFrame(self.frame_2)
        self.Right.setMinimumSize(QtCore.QSize(55, 0))
        self.Right.setMaximumSize(QtCore.QSize(55, 16777215))
        self.Right.setStyleSheet("border:0 ; \n"
"background-color: rgb(211, 215, 207);")
        self.Right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Right.setObjectName("Right")
        self.horizontalLayout.addWidget(self.Right)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("border:0;\n"
"background-color: rgb(211, 215, 207);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(370, 0, 120, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Home.setText(_translate("MainWindow", "Home"))
        self.NewUnidade.setText(_translate("MainWindow", "Add"))
        self.Account.setText(_translate("MainWindow", "Account"))
        self.Settings.setText(_translate("MainWindow", "Settings"))
        self.Sensor1Button.setText(_translate("MainWindow", "Sensor BME"))
        self.Sensor1Label.setText(_translate("MainWindow", "11"))
        self.label.setText(_translate("MainWindow", "Home Sensors"))
import file_rc_rc
