# Generated by Django 3.1.7 on 2021-02-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_unidades',
            name='data_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.unidadesensorial'),
            preserve_default=False,
        ),
    ]
