# Generated by Django 3.1.7 on 2021-02-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dados_unidades_data_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_unidades',
            old_name='data_id',
            new_name='Unidade_data',
        ),
    ]
