# Generated by Django 3.1.7 on 2021-02-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210228_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_unidades',
            old_name='Unidade_data',
            new_name='data_Unidade',
        ),
    ]
