# Generated by Django 3.1.7 on 2021-03-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210228_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_unidades',
            name='data_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
