# Generated by Django 3.1.7 on 2021-03-10 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210310_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_unidades',
            name='data_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
